[project]
name = "payroll-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.8"
dependencies = [
    "aiohttp>=3.12.15",
    "reflex>=0.8.7",
    "reflex-calendar>=0.0.6",
    "supabase>=2.18.0",
]

[dependency-groups]
dev = [
    "aioresponses>=0.7.8",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "requests-mock>=1.12.1",
    "ruff>=0.12.10",
]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:Config file.*not found.*:UserWarning"
]

[tool.ruff]
exclude = [".venv"]
respect-gitignore = true
line-length = 120
lint.ignore = [
    "F403"
]
