"""Stub file for reflex_react_select/react_select.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from typing import Annotated, Any, Callable, Dict, Literal, Mapping, Optional, Sequence, Union

import reflex
import reflex as rx
from reflex.components.component import NoSSRComponent
from reflex.event import EventChain, EventHandler, EventSpec, EventType, KeyInputInfo, PointerEventInfo
from reflex.style import Style
from reflex.vars.base import Var
from reflex_components_core.core.breakpoints import Breakpoints

class ReactSelect(NoSSRComponent):
    def add_style(self): ...
    @classmethod
    def create(
        cls,
        *children,
        class_name_prefix: Var[str] | str | None = None,
        name: Var[str] | str | None = None,
        input_id: Var[str] | str | None = None,
        options: Var[list[dict[str, str]]] | list[dict[str, str]] | None = None,
        value: Var[str] | str | None = None,
        content_editable: Var[bool] | bool | None = None,
        is_searchable: Var[bool] | bool | None = None,
        is_clearable: Var[bool] | bool | None = None,
        is_multi: Var[bool] | bool | None = None,
        default_value: Var[dict[str, str] | None] | dict[str, str] | None = None,
        default_input_value: Var[str | None] | str | None = None,
        placeholder: Var[str] | str | None = None,
        no_options_message: FunctionVar[Any] | None = None,
        menu_is_open: Var[bool | None] | bool | None = None,
        default_menu_is_open: Var[bool] | bool | None = None,
        close_menu_on_select: Var[bool] | bool | None = None,
        max_menu_height: Var[int | None] | int | None = None,
        control_style: Style | Var[Style | dict | None] | dict | None = None,
        control_focused_style: Style | Var[Style | dict | None] | dict | None = None,
        input_container_style: Style | Var[Style | dict | None] | dict | None = None,
        single_value_style: Style | Var[Style | dict | None] | dict | None = None,
        multi_value_style: Style | Var[Style | dict | None] | dict | None = None,
        multi_value_label_style: Style | Var[Style | dict | None] | dict | None = None,
        menu_style: Style | Var[Style | dict | None] | dict | None = None,
        option_selected_style: Style | Var[Style | dict | None] | dict | None = None,
        option_focused_style: Style | Var[Style | dict | None] | dict | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Var | Any] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_change: Optional[EventType[Any]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_input_change: Optional[EventType[Any]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "ReactSelect":
        """Create the component.

        Args:
            *children: The children of the component.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: custom attribute
            **props: The props of the component.

        Returns:
            The component."""
        ...

react_select = ReactSelect.create
